import { useCallback, useEffect, useState } from "react";
import { Check, CreditCard, ExternalLink, FileCheck2, FileText, LockKeyhole, MapPin, RefreshCw, UploadCloud, UserRound } from "lucide-react";
import { api, endpoints, unwrap } from "./api";

const empty = { firstName:"",lastName:"",phone:"",avatarUrl:"",dateOfBirth:"",gender:"",address:{line1:"",line2:"",country:"",state:"",city:"",postalCode:""},documents:{panCardUrl:"",aadhaarCardUrl:"",cancelledChequeUrl:""},payout:{method:"bank",accountHolderName:"",bankName:"",accountNumber:"",ifscCode:"",upiId:""} };
const merge = (profile={}) => ({ ...empty, ...(profile.user?.profile||{}), phone:profile.user?.mobile||"", dateOfBirth:profile.details?.dateOfBirth?.slice?.(0,10)||"", gender:profile.details?.gender||"", address:{...empty.address,...profile.details?.address}, documents:{...empty.documents,...profile.details?.documents}, payout:{...empty.payout,...profile.details?.payout} });

export default function ProfilePage({ session }) {
  const [record,setRecord]=useState(null); const [form,setForm]=useState(empty); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const [uploading,setUploading]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const next=unwrap(await api.get(endpoints.profile));setRecord(next);setForm(merge(next));}catch(err){setError(err?.response?.data?.message||"Unable to load profile.");}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const set=(key,value)=>setForm((current)=>({...current,[key]:value}));
  const setGroup=(group,key,value)=>setForm((current)=>({...current,[group]:{...current[group],[key]:value}}));
  const uploadFile=async(key,file,{image=false}={})=>{if(!file)return;setUploading(key);setError("");setMessage("");try{const body=new FormData();body.append("file",file);body.append("module","influencer-kyc");body.append(image?"imageType":"documentKey",key);const uploaded=unwrap(await api.post(image?endpoints.uploadImage:endpoints.uploadDocument,body));const url=uploaded?.url||uploaded?.imageURL||uploaded?.documentURL||uploaded?.image?.url||uploaded?.document?.url;if(!url)throw new Error("Upload response did not contain a file URL");const payload=image?{avatarUrl:url}:{documents:{[key]:url}};const next=unwrap(await api.patch(endpoints.profile,payload));setRecord(next);setForm(merge(next));setMessage(`${image?"Profile photo":"KYC document"} uploaded and saved successfully.`);}catch(err){setError(err?.response?.data?.message||err?.message||"Unable to upload file.");}finally{setUploading("");}};
  const submit=async(event)=>{event.preventDefault();setSaving(true);setError("");setMessage("");try{const next=unwrap(await api.patch(endpoints.profile,form));setRecord(next);setForm(merge(next));setMessage("Profile submitted successfully. KYC and payout changes may require Admin approval.");}catch(err){setError(err?.response?.data?.message||"Unable to update profile.");}finally{setSaving(false);}};
  if(loading)return <div className="table-card loading-card"><div/><div/><div/></div>;
  return <><div className="page-heading"><div><h1>My Profile</h1><p>Complete your Referral Partner account and payout information.</p></div><button className="button secondary" onClick={load}><RefreshCw size={16}/>Reload</button></div>
    <div className="profile-readiness"><div><span>KYC verification</span><strong className={`status-pill ${record?.kycStatus}`}>{String(record?.kycStatus||"pending").replaceAll("_"," ")}</strong><small>Required before withdrawing coins</small></div><div><span>Payout details</span><strong className={`status-pill ${record?.payoutProfile?.status}`}>{String(record?.payoutProfile?.status||"not submitted").replaceAll("_"," ")}</strong><small>{record?.payoutProfile?.bankOrUpiConfigured?"Bank or UPI details configured":"Add bank or UPI details below"}</small></div></div>
    <div className="identity-strip"><div><LockKeyhole size={18}/><span>Referral ID</span><strong>{session.influencerId}</strong></div><div><LockKeyhole size={18}/><span>Referral Code</span><strong>{record?.primaryCode?.code||"Not assigned"}</strong></div><div><LockKeyhole size={18}/><span>Login Email</span><strong>{record?.user?.email||"—"}</strong></div><small>Referral ID, code and login email are controlled by Admin.</small></div>
    <form className="profile-form" onSubmit={submit}>
      <FormSection number="01" icon={<UserRound size={17}/>} title="Basic Information"><Field label="First Name" value={form.firstName} onChange={(v)=>set("firstName",v)} required/><Field label="Last Name" value={form.lastName} onChange={(v)=>set("lastName",v)}/><Field label="Phone Number" value={form.phone} onChange={(v)=>set("phone",v)} required/><Field label="Date of Birth" type="date" value={form.dateOfBirth} onChange={(v)=>set("dateOfBirth",v)}/><Select label="Gender" value={form.gender} onChange={(v)=>set("gender",v)} options={["","male","female","other","prefer_not_to_say"]}/><UploadField label="Profile Picture" value={form.avatarUrl} accept="image/jpeg,image/png,image/webp,image/gif" uploading={uploading==="avatarUrl"} onFile={(file)=>uploadFile("avatarUrl",file,{image:true})}/></FormSection>
      <FormSection number="02" icon={<MapPin size={17}/>} title="Address Details"><Field label="Address Line 1" value={form.address.line1} onChange={(v)=>setGroup("address","line1",v)} wide/><Field label="Address Line 2" value={form.address.line2} onChange={(v)=>setGroup("address","line2",v)}/><Field label="Country" value={form.address.country} onChange={(v)=>setGroup("address","country",v)}/><Field label="State" value={form.address.state} onChange={(v)=>setGroup("address","state",v)}/><Field label="City" value={form.address.city} onChange={(v)=>setGroup("address","city",v)}/><Field label="PIN / Zip Code" value={form.address.postalCode} onChange={(v)=>setGroup("address","postalCode",v)}/></FormSection>
      <FormSection number="03" icon={<FileText size={17}/>} title="KYC Documents"><UploadField label="PAN Card" value={form.documents.panCardUrl} uploading={uploading==="panCardUrl"} onFile={(file)=>uploadFile("panCardUrl",file)}/><UploadField label="Aadhaar Card" value={form.documents.aadhaarCardUrl} uploading={uploading==="aadhaarCardUrl"} onFile={(file)=>uploadFile("aadhaarCardUrl",file)}/><UploadField label="Cancelled Cheque" value={form.documents.cancelledChequeUrl} uploading={uploading==="cancelledChequeUrl"} onFile={(file)=>uploadFile("cancelledChequeUrl",file)}/></FormSection>
      <FormSection number="04" icon={<CreditCard size={17}/>} title="Payout Information"><Select label="Payout Method" value={form.payout.method} onChange={(v)=>setGroup("payout","method",v)} options={["bank","upi"]}/><Field label="Account Holder Name" value={form.payout.accountHolderName} onChange={(v)=>setGroup("payout","accountHolderName",v)}/>{form.payout.method==="bank"?<><Field label="Bank Name" value={form.payout.bankName} onChange={(v)=>setGroup("payout","bankName",v)}/><Field label="Account Number" value={form.payout.accountNumber} onChange={(v)=>setGroup("payout","accountNumber",v)}/><Field label="IFSC Code" value={form.payout.ifscCode} onChange={(v)=>setGroup("payout","ifscCode",v)}/></>:<Field label="UPI ID" value={form.payout.upiId} onChange={(v)=>setGroup("payout","upiId",v)}/>}</FormSection>
      {error&&<div className="form-message error-state">{error}</div>}{message&&<div className="form-message success-state">{message}</div>}<div className="form-actions"><button type="button" className="button secondary" onClick={load}>Cancel changes</button><button className="button gold" disabled={saving}><Check size={16}/>{saving?"Saving…":"Save Profile"}</button></div>
    </form></>;
}
function FormSection({number,icon,title,children}){return <section className="form-section"><div className="form-section-title"><b>{number}</b>{icon}<h2>{title}</h2><span/></div><div className="form-grid">{children}</div></section>}
function Field({label,value,onChange,type="text",required=false,wide=false}){return <label className={wide?"field wide":"field"}><span>{label}{required&&" *"}</span><input type={type} value={value||""} onChange={(e)=>onChange(e.target.value)} required={required}/></label>}
function Select({label,value,onChange,options}){return <label className="field"><span>{label}</span><select value={value||""} onChange={(e)=>onChange(e.target.value)}>{options.map((option)=><option key={option} value={option}>{option?option.replaceAll("_"," "):"Select"}</option>)}</select></label>}
function UploadField({label,value,onFile,uploading,accept="application/pdf,image/jpeg,image/png,image/webp"}){return <div className="upload-field"><span className="upload-label">{label}</span><label className={`upload-box ${value?"has-file":""}`}><input type="file" accept={accept} onChange={(event)=>{const file=event.target.files?.[0];onFile(file);event.target.value="";}} disabled={uploading}/>{value?<FileCheck2 size={25}/>:<UploadCloud size={25}/>}<strong>{uploading?"Uploading to cloud…":value?"Document uploaded":"Choose file to upload"}</strong><small>{value?"Click to replace":"PDF, JPG, PNG or WEBP"}</small></label>{value&&<a className="uploaded-link" href={value} target="_blank" rel="noreferrer"><ExternalLink size={13}/>View uploaded file</a>}</div>}
